### ISSUE TITLE
accordion opens then immediately hides content

### ISSUE THREAD

**Issue by gottaloveit** [mdbootstrap/TW-Elements#1085]
This is happening on your [docs page](https://tailwind-elements.com/docs/standard/components/accordion/) on all the examples and even on the Show Code buttons.  Subsequently it's also happening when I try to implement the accordion in my project.

**Comment by gottaloveit** [comment]
related
#1082 
#1081

**Comment by daveb1014** [comment]
Been a while between major code updates, so hopefully the project is still alive, but this workaround has worked for me - I just add the following CSS to the page:

`.accordion-collapse.show { visibility: visible !important; }`

This seems to fix the issue for accordions anyway. As others have observed, the issue is that expanded/non-collapsed "collapsible" elements have the "collapse" class applied, which applies the style "visibility: collapse", which basically makes content invisible without changing its shape/bounding box.

The CSS rule which causes this seems to be:

`.collapse {
  visibility: collapse;
}`

whereas in some older code I have (still 1.0.0-alpha11) there is:

`.collapse:not(.show) {
    display: none
}`

I haven't dug through the modules to work out where this class is being applied though.

**Comment by daveb1014** [comment]
This might actually be caused by a bug in tailwind css between version v3.1.8 (working) and v3.2.1 (broken).

**Comment by codecapsules** [comment]
Yes all the library is broken for now ... we can't copy nothing in the website and the library himself is broken ^^
We need to wait :)

**Comment by makkinga** [comment]
> related #1082 #1081

also #1089, #1086, and probably #1083

Broke [here](https://github.com/tailwindlabs/tailwindcss/commit/cc1be47a4fa2de74bc63b0b123f335271ec1bc68) with Tailwind 3.2.0

**Comment by LocalHeroPro** [comment]
I quick fixed it by:
```css
.collapse.show {
    visibility: unset;
}
```
But waiting for official fix.

tailwindcss: v3.2.2
tw-elements: 1.0.0-alpha12

**Comment by FileSoft-us** [comment]
> I quick fixed it by:
> 
> ```css
> .collapse.show {
>     visibility: unset;
> }
> ```
> 
> But waiting for official fix.
> 
> tailwindcss: v3.2.2 tw-elements: 1.0.0-alpha12

thanks i added !important

`.collapse.show {
    visibility: unset !important;
}`

**Comment by smolenski-mikolaj** [comment]
The problem should be fixed with the latest release.

**Comment by LocalHeroPro** [comment]
Nope, issue still occurred.
tailwindcss: v3.3.1
tw-elements: 1.0.0-beta2
